<pre class='metadata'>
Title: GDI Harmonised Minimal Data Model
Shortname: GDI HMD
level: none
Status: LD
URL: https://health-ri.github.io/HarmonisedMinimalDatamodel/v2.0
Previous Version: https://health-ri.github.io/HarmonisedMinimalDatamodel/v1.1
Status Text: status text
Editor: Ana Konrad
Editor: Hannah Neikes
Editor: Jeroen Beliën
Editor: Joeri van der Velde
Editor: Abhishek Nayak
Editor: Aedin Culhane
Warning: not ready

Abstract: <img src="src/images/gdi-logo.svg" alt="GDI-logo" title="GDI-logo" width="300"> <br/> Some context about the GDI HMD.
Markup Shorthands: markdown yes, css no
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/style_tables_general.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/introduction.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/Subject.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/Diagnosis.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/Sample.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/TNM.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/SampleRelation.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/Sequence.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/DigitalResource.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/Variant.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/TargetGene.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/Treatment.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/Biomarker.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/mainClasses/EnvironmentalExposure.md
</pre>

<pre class=include>
path: https://raw.githubusercontent.com/Health-RI/HarmonisedMinimalDatamodel/tree/v2.0/src/new/matches.md
</pre>