# This workflow converts your bikeshed (.bs) file to html and pushes to gh-pages

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          SOURCE: index.bs
          DESTINATION: index.html
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          SOURCE: index_v1.1.bs
          DESTINATION: v1.1/index.html
          BIKESHED_ARGS: "--allow=raw.githubusercontent.com"
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          SOURCE: index_v2.0.bs
          DESTINATION: v2.0/index.html